apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: itinerarios
spec:
  replicas: 1
  selector:
    matchLabels: { app: rabbitmq }
  template:
    metadata:
      labels: { app: rabbitmq }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          command: ["sh", "-c", "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"]
          ports:
            - { containerPort: 5672, name: amqp }
            - { containerPort: 15672, name: mgmt }
            - { containerPort: 15692, name: metrics }
          readinessProbe:
            exec: { command: ["rabbitmq-diagnostics", "-q", "ping"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["rabbitmq-diagnostics", "-q", "ping"] }
            initialDelaySeconds: 20
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: itinerarios
spec:
  selector: { app: rabbitmq }
  ports:
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: mgmt, port: 15672, targetPort: 15672 }
    - { name: metrics, port: 15692, targetPort: 15692 }
